### ISSUE TITLE
BUG - unhelpful error message when insufficient API scopes

### ISSUE THREAD

**Issue by trev-dev** [hughrun/ephemetoot#46]
**Description**
When I attempt to use ephemetoot for the first time using Python 3.8.5 I get a `ModuleNotFound` error.

Please only log one bug per issue.

**Environment (please complete the following information):**
- OS Manjaro Linux
- Python 3.8.5

**To Reproduce**
pip install ephemetoot in any way you'd like other than with `sudo`. Was able to replicate it with `--user`, virtualenv and pipenv.

**Expected behavior**
I get to use ephemetoot

**Actual behavior**
I don't get to use ephemetoot

**Screenshots**
Nah

**Additional context**
```bash
  File "/home/user/.local/share/virtualenvs/ephemetoot-7ki6mRLC/bin/ephemetoot", line 5, in <module>
    from ephemetoot.console import main
  File "/home/trev/.local/share/virtualenvs/ephemetoot-7ki6mRLC/lib/python3.8/site-packages/ephemetoot/console.py", line 36, in <module>
    from lib import ephemetoot
ModuleNotFoundError: No module named 'lib'
```

**Comment by hughrun** [comment]
Apologies @trev-dev I prematurely updated the docs: up until last week `ephemetoot` was not in pypi and install was via git.

The first version uploaded to pipy (v2.6.1) is borked because I didn't know what I was doing. 

Right now you can resolve the error by uninstalling and then installing the **alpha version 3** but you have to pin the exact version because it's a pre-release:

```
pip uninstall ephemetoot
pip install ephemetoot==3.0.0-alpha.0
```

I expect to have a 'proper' v3.0.0 in pypi by the end of this weekend. The current docs should work for 3.0.0a0.

**Comment by trev-dev** [comment]
Thank you!

**Comment by trev-dev** [comment]
LOL, the alpha version is throwing a 50x error when trying to connect to my instance. I'll wait for the release.

**Comment by hughrun** [comment]
@trev-dev that's...unexpected. Do you mind posting your config (but not your real access token, obvs)? This is either your config file being not quite right, your server being weird, or a new and exciting bug.

**Comment by hughrun** [comment]
there is also now a new beta version which may or may not help.

**Comment by trev-dev** [comment]
It tried the beta and it's the same result. Here's my config :D Running `ephemetoot --test`
```yaml
-
  access_token: redacted
  username: trevdev
  base_url: mastodon.technology
  days_to_keep: 182
  keep_pinned: true
  hashtags_to_keep:
    - #python
    - #javascript
    - #vuejs
    - #react
    - #teaching
    - #scratch
    - #pygame
    - #privacy
    - #security
    - #linux
    - #foss
    - #arch
    - #debian
    - #opensource
    - #reactjs
    - #webdev
    - #pelican
    - #100daysofcode
    - #diaspora
    - #mastodon
    - #django
    - #emacs
    - #vim
    - #neovim
  archive: ~/Downloads
```
